<a href="https://colab.research.google.com/github/udghosh/Practice/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
from numpy import random
x = random.randint(100)
print(x)

53


In [ ]:
arr3=np.array([[1,2],[3,4],[5,6]])
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

In [ ]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
a = np.arange(1,20,1)
s = slice(2,7)
print(a)
print(a[s])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[3 4 5 6 7]


In [ ]:
a = np.arange(1,20,1)
print(a[a>5])

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
a = np.char.multiply("hello",5)
print(a)

hellohellohellohellohello


In [ ]:
li1 = ["hello"]
li2 = ["uday"]
a = np.char.add(li1,li2)
print(a)

['hellouday']


In [ ]:
a = np.char.capitalize("bye")
print(a)

Bye


In [ ]:
a = np.char.split("hello-folks-I-am-Uday",'-')
print(a)

['hello', 'folks', 'I', 'am', 'Uday']


In [ ]:
print(np.char.strip('hello hash has a hash','h'))
print(np.char.strip(['ab','aab','aaab'],'a'))


ello hash has a has
['b' 'b' 'b']


In [ ]:
print(np.char.join(':','hello folks'))

h:e:l:l:o: :f:o:l:k:s


In [ ]:
print(np.power(2,3))

8


In [ ]:
import numpy as np
import pandas as pd
n_studs = 300
HouseOne = pd.DataFrame({
    "Name":["Name_"+str(i) for i in range(n_studs)],
    "Subject":np.random.choice(["Subject_"+str(i) for i in range(6)], size=n_studs),
    "Rating":np.random.uniform(low=1, high=10, size=n_studs)
})
